version: "3.9"

services:
  proxy:
    build: ./part3-proxy
    container_name: proxy
    ports:
      - "5557:5557"
      - "5558:5558"

  server:
    build: ./part3-server
    container_name: server
    depends_on:
      - proxy
    volumes:
      - ./data:/app/data

  bot:
    build: ./part3-bot
    depends_on:
      - server
      - proxy
    scale: 3
    volumes:
      - ./data:/app/data

  client:
    build: ./part3-client
    depends_on:
      - server
